sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_rec/eps0.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_rec/eps2.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_rec/eps4.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_rec/eps6.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_rec/eps8.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_rec/eps10.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_rec/eps12.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_rec/eps14.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_rec/eps16.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_rec/eps18.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_rec/eps20.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_rec/eps22.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_rec/eps24.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_rec/eps26.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_rec/eps28.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_rec/eps30.job
