#!/bin/bash
#SBATCH -p pearl
#SBATCH --job-name=@JNAME@
#SBATCH --time=3-00:00
#SBATCH -n 1
#SBATCH --gres=gpu:1
#SBATCH --output=@OUTPUT@
#SBATCH --mem-per-cpu=20G
#SBATCH --mem-per-gpu=20G

cd @MAINPATH@
