sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_kl/eps1.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_kl/eps3.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_kl/eps5.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_kl/eps7.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_kl/eps9.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_kl/eps11.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_kl/eps13.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_kl/eps15.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_kl/eps17.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_kl/eps19.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_kl/eps21.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_kl/eps23.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_kl/eps25.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_kl/eps27.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_kl/eps29.job
sbatch /Users/kuangdai/stfc/fundamental/disentangling-vae/e_vae_proj/evae_dsprites/jobs_kl/eps31.job
